### ISSUE TITLE
Docker image:  LDES_CLIENT_CLI_TAG=20230206t0943, [main] ERROR org.springframework.boot.SpringApplication - Application run failed

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESWorkbench-Services#102]
**This issue only occurs on LDES_CLIENT_CLI_TAG=20230206t0943 (sprint 20) not LDES_CLIENT_CLI_TAG=20230130T1553 (sprint 19)**

**Prerequisite:**

Docker images:

- LDES_CLIENT_CLI_TAG=20230206t0943
- LDES_SERVER_TAG=20230214t1234

Modify docker tag:  `image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldes-cli:${LDES_CLIENT_CLI_TAG:-20230206t0943`} in the [docker-compose.yml](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/demos/ldes-server-caching/docker-compose.yml) ) to use the buggy docker image tag: 20230206t094

**Scenario:**
1. Follow the step by step scenario of: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/demos/ldes-server-caching => A ldes stream is posted on the Ldes server running on the port 8080, the root of the view is at http://localhost:8080/mobility-hindrances/by-time
2.  (Step: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/demos/ldes-server-caching#verify-http-304-handling) launch the LDES client to print the ldes stream to the ldes client's console, by running the command line 

```
docker compose create ldes-cli
docker compose up ldes-cli -d

```

**Current result:**
The docker image ldes-client cli cannot start with the error:
```

setup-caching_ldes-client-cli  | [main] INFO be.vlaanderen.informatievlaanderen.ldes.client.cli.Application - Starting Application using Java 18.0.1.1 with PID 1 (/ldes-client-cli/target/ldes-client-cli-jar-with-dependencies.jar started by ldes in /)
setup-caching_ldes-client-cli  | [main] INFO be.vlaanderen.informatievlaanderen.ldes.client.cli.Application - No active profile set, falling back to 1 default profile: "default"
setup-caching_ldes-client-cli  | [main] INFO be.vlaanderen.informatievlaanderen.ldes.client.cli.Application - Started Application in 1.075 seconds (process running for 1.194)
setup-caching_ldes-client-cli  | [main] INFO be.vlaanderen.informatievlaanderen.ldes.client.endpointrequester.EndpointRequester - Determining starting node for: http://localhost:8080/mobility-hindrances/by-time
setup-caching_ldes-client-cli  | [main] INFO be.vlaanderen.informatievlaanderen.ldes.client.endpointrequester.EndpointRequester - Selected starting node: http://localhost:8080/mobility-hsetup-caching_ldes-client-cli  | [main] ERROR org.springframework.boot.SpringApplication - Application run failed
setup-caching_ldes-client-cli  | java.lang.IllegalStateException: Failed to execute CommandLineRunner
setup-caching_ldes-client-cli  |        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:770)
setup-caching_ldes-client-cli  |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
setup-caching_ldes-client-cli  |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
setup-caching_ldes-client-cli  |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)
setup-caching_ldes-client-cli  |        at be.vlaanderen.informatievlaanderen.ldes.client.cli.Application.main(Application.java:24)
setup-caching_ldes-client-cli  | Caused by: be.vlaanderen.informatievlaanderen.ldes.client.exceptions.LdesPersistenceException: Unable to connect to persistence database ldesclientstate.db
setup-caching_ldes-client-cli  |        at be.vlaanderen.informatievlaanderen.ldes.client.state.SqlitePersistedLdesStateManager.connect(SqlitePersistedLdesStateManager.java:82)
setup-caching_ldes-client-cli  |        at be.vlaanderen.informatievlaanderen.ldes.client.state.SqlitePersistedLdesStateManager.executeCount(SqlitePersistedLdesStateManager.java:330)    
setup-caching_ldes-client-cli  |        at be.vlaanderen.informatievlaanderen.ldes.client.state.SqlitePersistedLdesStateManager.isQueuedFragment(SqlitePersistedLdesStateManager.java:138)setup-caching_ldes-client-cli  |        at be.vlaanderen.informatievlaanderen.ldes.client.state.LdesStateManager.queueFragment(LdesStateManager.java:145)
setup-caching_ldes-client-cli  |        at be.vlaanderen.informatievlaanderen.ldes.client.services.LdesServiceImpl.queueFragment(LdesServiceImpl.java:74)
setup-caching_ldes-client-cli  |        at be.vlaanderen.informatievlaanderen.ldes.client.cli.services.LdesClientCli.start(LdesClientCli.java:35)
setup-caching_ldes-client-cli  |        at be.vlaanderen.informatievlaanderen.ldes.client.cli.Application.run(Application.java:33)
setup-caching_ldes-client-cli  |        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:767)
setup-caching_ldes-client-cli  |        ... 5 more
setup-caching_ldes-client-cli  | Caused by: java.sql.SQLException: opening db: 'ldesclientstate.db': Permission denied
setup-caching_ldes-client-cli  |        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:269)
setup-caching_ldes-client-cli  |        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
setup-caching_ldes-client-cli  |        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
setup-caching_ldes-client-cli  |        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
setup-caching_ldes-client-cli  |        at org.sqlite.JDBC.createConnection(JDBC.java:104)
setup-caching_ldes-client-cli  |        at org.sqlite.JDBC.connect(JDBC.java:77)
setup-caching_ldes-client-cli  |        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
setup-caching_ldes-client-cli  |        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
setup-caching_ldes-client-cli  |        at be.vlaanderen.informatievlaanderen.ldes.client.state.SqlitePersistedLdesStateManager.connect(SqlitePersistedLdesStateManager.java:72)
setup-caching_ldes-client-cli  |        ... 12 more
setup-caching_ldes-client-cli exited with code 1
```

**Expected result:**
There should be no error

Please let me know if you can reproduce the issue
Thanks
XD

**Comment by xdxxxdx** [comment]
This issue doesn't occur on the Sprint 21 tag: LDES_CLIENT_CLI_TAG = 20230222T0959

**Comment by xdxxxdx** [comment]
As the issue doesn't occur on the Sprint 21 tag: LDES_CLIENT_CLI_TAG = 20230222T0959. 
Therefore, I close the issue.
